spring.application.name=book-service

server.error.include-message=always

#PostgreSQL by aiven.io
spring.datasource.url=jdbc:postgresql://pg-339bc558-eddfish.d.aivencloud.com:22423/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_PASS}

#JPA Hibernate
spring.jpa.hibernate.ddl-auto=update

#Dev mode
spring.jpa.show-sql=true
